# Empty example values for postal-rest.
# This is a YAML-formatted file.
# Copy this file and declare your own variables to be passed into the templates.
---
replicaCount: 1

image:
  repository: 'docker-repo.bloomington.in.gov/cob/postal-rest'
  tag: <tag here>
  pullPolicy: Always
nameOverride: ""
fullnameOverride: ""

config:
  base_uri: "/postal-rest"

serviceAccount:
  create: false
  annotations: {}

service:
  type: 'ClusterIP'
  port:       8080
  targetPort: 8080

ingress:
  enabled: true
  hosts:
    - host: example.local
      paths: ["/postal-rest"]

  tls:
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80
...
